// Questions
export const RECEIVE_QUESTIONS = "RECEIVE_QUESTIONS";
export const ADD_ANSWER = "ADD_ANSWER";
export const ANSWER_QUESTION_SUCCESS = "ANSWER_QUESTION_SUCCESS";
export const ANSWER_QUESTION_FAIL = "ANSWER_QUESTION_FAIL";
export const SAVE_QUESTION_SUCCESS = "SAVE_QUESTION_SUCCESS";

// Users
export const RECEIVE_USERS = "RECEIVE_USERS";
export const ANSWER_QUESTION_SUCCESS_USER = "ANSWER_QUESTION_SUCCESS_USER";
export const SAVE_QUESTION_SUCCESS_USER = "SAVE_QUESTION_SUCCESS_USER";

//Authed User
export const SET_AUTHED_USER = "SET_AUTHED_USER";
export const REMOVE_AUTHED_USER = "REMOVE_AUTHED_USER";
